  products-service:
    build:
      context: ./services/orders
    container_name: order-service
    ports:
      - "5000:5000"
    environment:
      - DB_URI=mongodb://mongo:27017/orders
      - PORT=5000
    depends_on:
      - mongo
