# Base Image
FROM node:18

# Set Working Directory
WORKDIR /src

# Copy Package file and Install Dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port 
EXPOSE 3002

# Start the application
CMD ["npm", "start"]