# Use the official Node.js LTS image as the base
FROM node:18

# Set the working directory inside the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Copy tsconfig.json to the working directory
COPY tsconfig.json ./

COPY ../../tsconfig.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to /app/src
COPY . /app

# Change the working directory to /app/src
WORKDIR /app/src

# Expose the port your service listens on
EXPOSE 3001

# Define environment variables (optional)
ENV NODE_ENV=production

# Command to start the application
CMD ["npm", "start"]
